### ISSUE TITLE
httpx ReadTimeout can be raised by client.send_notification skipping OneSignalHTTPError

### ISSUE THREAD

**Issue by ryanbabbly** [zeyneloz/onesignal_sdk#14]
Hi, we're using onesignal_sdk 2.0.0 with django 3.0 and sending some pushes from celery (v4.4.2) using code that looks something like this:

```python
client = Client(
    app_id=settings.ONESIGNAL_APP_ID, rest_api_key=settings.ONESIGNAL_API_KEY
)

try:
    response = client.send_notification(notification_body)
    logging.info(f'OneSignal response: {response.body}')

except OneSignalHTTPError as e:
    # Errors are HTTP status codes
    if str(e.status_code).startswith('5'):
        logging.warn(f'Retrying one signal because error: {e}')
        raise OneSignalRetryError(e)
    else:
        logging.error(
            f'{e.status_code} from OneSignal API with message {e.message}'
        )
```

And in sentry we've been getting this exception:

```bash
ReadTimeout: The read operation timed out
  File "httpx/_exceptions.py", line 342, in map_exceptions
    yield
  File "httpx/_client.py", line 798, in _send_single_request
    ) = transport.request(
  File "httpcore/_sync/connection_pool.py", line 188, in request
    response = connection.request(
  File "httpcore/_sync/connection.py", line 96, in request
    return self.connection.request(method, url, headers, stream, timeout)
  File "httpcore/_sync/http11.py", line 73, in request
    ) = self._receive_response(timeout)
  File "httpcore/_sync/http11.py", line 130, in _receive_response
    event = self._receive_event(timeout)
  File "httpcore/_sync/http11.py", line 160, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
ReadTimeout: The read operation timed out
  File "celery/app/base.py", line 487, in run
    return task._orig_run(*args, **kwargs)
  File "core/tasks.py", line 112, in _dispatch_push_notification
    client.send_notification(notification_body)
  File "onesignal_sdk/client.py", line 429, in send_notification
    return basic_auth_request(**self._kwargs_send_notification(notification_body))
  File "onesignal_sdk/request.py", line 37, in basic_auth_request
    return _handle_response(httpx.request(method, url, **request_kwargs))
  File "httpx/_api.py", line 89, in request
    return client.request(
  File "httpx/_client.py", line 673, in request
    return self.send(
  File "httpx/_client.py", line 703, in send
    response = self._send_handling_redirects(
  File "httpx/_client.py", line 732, in _send_handling_redirects
    response = self._send_handling_auth(
  File "httpx/_client.py", line 769, in _send_handling_auth
    response = self._send_single_request(request, timeout)
  File "httpx/_client.py", line 792, in _send_single_request
    (
  File "contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "httpx/_exceptions.py", line 359, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
```

For now I'm going to try to catch the exception directly from httpx, or putting a retry on all exceptions, but this seems like a bug or something I'm misunderstanding in my setup.

Please advise how to handle this error, thank you.

**Comment by ryanbabbly** [comment]
This is still an issue and it has proven difficult to figure out exactly what exception to catch here. Is anyone seeing this and able to advise?

**Comment by AlexProber** [comment]
I am having the same issue and still not finding a solution - did anyone solve this?

**Comment by mikelytvynenko** [comment]
Same thing, guys. Same questions...

**Comment by ahmedesmail07** [comment]
@ryanbabbly 
did you find any solution for this?
i got the same error here.

**Comment by chenx-07** [comment]
I encountered a similar issue. And it finally worked out when I set timeout explicitly for client httpx post.

For example, when I used google a2a protocol and ran the demos, I got "read time out", and I solved it by setting a longer timeout explicitly for client source code.
error:
```
An error occurred: Traceback (most recent call last):
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\http11.py", line 136, in handle_async_request
    raise exc
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\http11.py", line 106, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_async\http11.py", line 217, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "D:\Program Files\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\examples\langgraph\test_client.py", line 156, in main
    await run_single_turn_test(client)  # error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\examples\langgraph\test_client.py", line 67, in run_single_turn_test
    send_response: SendMessageResponse = await client.send_message(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\src\a2a\client\client.py", line 102, in send_message
    **await self._send_request(A2ARequest(request))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\src\a2a\client\client.py", line 134, in _send_request
    response = await self.httpx_client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1859, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\Program Files\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\project\a2a_google\Agent2Agent\a2a-python-sdk\.venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

solution:  add timeout
```Python
    async def _send_request(self, request: A2ARequest) -> dict[str, Any]:
        try:
            response = await self.httpx_client.post(
                self.url, json=request.root.model_dump(mode='json'), timeout=10.0
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            raise A2AClientHTTPError(e.response.status_code, str(e)) from e
        except json.JSONDecodeError as e:
            raise A2AClientJSONError(str(e)) from e
```



Although my case is different from yours, I hope it could help you solve this problem.
